### ISSUE TITLE
Can't find datapacks

### ISSUE THREAD

**Issue by herointhestars** [NivOridocs/flowstone#8]
I'd like to edit the chances for different ores, but I can't find the registry/datapacks? It says they're at [I assume .minecraft]/data/<mod id or datapack name>/flowstone/generators, but there's nothing like that in the data folder, even after having played the game with this mod. Am I misunderstanding something?
By the way, I'm not sure if this counts as an issue, but I couldn't find a better place to ask. I hope this is alright. Thanks

**Comment by NivOridocs** [comment]
I think it is okay to ask here also because I don't know where else.

From my understanding, fabric loads mods' built-in datapacks directly from the jar files, so you can't really edit them. What you can do is create a new one and add that to your world while disabling the built-in ones.

For instance, if you want to *edit* the "Overworld Ores" built-in datapack, you can copy the original one from the source here on GitHub (the path to it is `src/main/resources/resourcepacks/overworld_ores/`), edit the copy, zip it, and add it to your world while disabling the enabled-by-default "Overworld Ores".

I hope my explanation is clear enough, and if it isn't, feel free to ask for clarification here below. Also, if you succeed, I'd like a comment still so to close the issue.

Ah, obviously, I am assuming that you're using at least Flowstone 6.2 for the built-in datapacks exists only from there onward.

**Comment by herointhestars** [comment]
Thank you, I was able to get it working :)
